const fs = require('fs')
const input = fs.readFileSync('/dev/stdin').toString().trim()
let result = Array.from({length : input}, (_ , i) => ' '.repeat(input - i -1) + '*'.repeat(i * 2 + 1))
let result_reverse = [...result].reverse()
result.shift()
console.log(result_reverse.join('\n'))
console.log(result.join('\n'))